### PR TITLE
Ceph 15.2.5

### PR DESCRIPTION
**Pull request by mvalois**
Fixes missing sub-dictionaries introduced in recent versions of Ceph (octopus).
I tried to be the most retro-compatible possible.
Requirement added: packaging, for Ceph versions comparison.

### CODE REVIEW

**Comment by k0ste** [comment]
We shouldn't do that. Is enough to check:

```python
    if 'osdmap' in cluster_status['osdmap']:
        # pre Octopus cluster
        osdmap = cluster_status['osdmap']['osdmap']
    else:
        # Octopus+ cluster
        osdmap = cluster_sataus['osdmap']
```

**Comment by mvalois** [comment]
I thought so, but there is still the `monMaps` which lacks information and I found it too dirty to put this in this `if`.

**Comment by k0ste** [comment]
What you mean lack of information? I was already paste example how to check for `osdmap` may be performed.

**Comment by mvalois** [comment]
```cluster_status['monmap']``` has been removed from API since octopus, so you need to retrieve both `osdmap` and `monmap` for the view to work.

**Comment by k0ste** [comment]
Understood, but for this we don't need to check versions of ceph cli. It's enough to check `osdmap` in `osdmap`.

**Comment by mvalois** [comment]
I've just edited to remove the dependencies. Now I just check for `osdmap` in `osdmap`.

**Comment by Crapworks** [comment]
Hey @mvalois,

thanks for working on this!

**Comment by mvalois** [comment]
Fine, it should fix #63.

**Pull request merged**
