### PR TITLE
OSD Utilization

### PR DESCRIPTION
**Pull request by nrm21**
This PR adds the OSD disk statistics and utilization when you hover over the OSD total cell.

[Screenshot link is attached.](http://imgur.com/a/pxytq)

### CODE REVIEW

**Comment by nrm21** [comment]
Hello? Any word on this?

Awesome you love it?
Wow this sucks?
Something in between?
:-)

**Comment by Crapworks** [comment]
Hi @nrm21,

sorry for the late reply, but I wasn't able to work on this project in quite a while. The main problem I see here, is the overhead for larger installations. Just as an example, in our setup we had 1400 disk setup and ceph osd df could take a bit to complete. In addition to that, in that case the popov would no be very helpful at all :) It would be ok for smaller setups, but I am trying to keep ceph-dash viable for all kinds of setups. Also from a "monitoring" point of view, you would get notifications if a disk is getting nearfull/full state, so there is not a real benefit for that. 

Cheers,
Christian

**Comment by nrm21** [comment]
Yeah I guess I see what you are saying.  I use mainly on 2 separate (but both smaller) setups where it seems to work just fine.  But I guess if there were 1400 osd's it would be kinda hard to scroll through that, if you even could.

Oh well, I mainly did it to scratch my own itch and figured if someone else could benefit it would be nice too.

**Comment by Crapworks** [comment]
Yeah, thats the cool thing about github! And I really appreciate any kind of contribution! So keep up the good work and thanks for helping to improve ceph-dash!

**Pull request closed without merging**
