### PR TITLE
Added read/write ops for Jewel release

### PR DESCRIPTION
**Pull request by maran**
As discussed in #28 a pull request to fix operations while still preserving backwards compatibility. 

Javascript is not my forté so please let me know if there are better ways to achieve this.

### CODE REVIEW

**Comment by Crapworks** [comment]
Hey!
Thank you for your work! I was thinking: Don't you think it would be a good idea to leave the html untouched and just add the ops for read and write together? For me, there is not really an advantage on having them seperate, since you already see the read/write throughput seperately. what do you think?

**Comment by maran** [comment]
For me having separate operations is really a benefit since throughput and operations don't always have to match. I'm fine with providing an other pull request that just adds the numbers though.

Perhaps if somebody else is lurking around we could get some votes on how to handle this? Not sure how popular this project is.

**Comment by Crapworks** [comment]
Hm, can you do me a favour and send me a screenshot how it looks with the split ops?

**Comment by maran** [comment]
This is the one from the PR.

one

This is the other iteration I tried.
two

**Comment by Crapworks** [comment]
Second one definitel looks better for me. If you could put this in a pr, I will merge it

**Comment by richarson** [comment]
Hi, just chimming in to vote for the split ops.

I also like the second version better but for consistency, could you swap read and write ops (or re-order write and read MB/s)?

I actually prefer it this way, but it's just a very minor nitpick:
Read (MB/s)
Write (MB/s)
Read (ops) Write (ops)

**Comment by maran** [comment]
I've updated the PR with the second screenshot. I also moved Write/Read ops around for @richarson (I agree this makes more sense). 

I feel that changing the wording further should be left to be decided by @Crapworks as owner of this project. I am fine with either way although I think that because the Write / second already displays MB in the data itself it seems a bit redundant.

**Comment by emagutu** [comment]
Second one looks better.

**Comment by Crapworks** [comment]
Thanks for your work maran! Just merged it.
Could someone else maybe have a look at it and confirm that everything looks fine? That would be cool!

**Comment by Crapworks** [comment]
Fixes #28

**Comment by maran** [comment]
Yeah I would love to see if it looks ok on pre-Jewel as well. No way to test that sadly.

Now I have you anyway is there any chance I could get you to take a look at Crapworks/collectd-ceph#3? I would love to fix that as well but I'm a bit out of my depth as to where things go wrong.

**Comment by richarson** [comment]
Thanks for this!
Re: the wording, don't worry, it was just an example with my hardwired syntax :)

I'll see if I can test it on my cluster (stil on Giant, planning the upgrade to Hammer and then to Jewel) and report back.

**Comment by richarson** [comment]
OK, I finally made some time to test this version and there's an empty "Read ops / second" that looks a bit out of place but nothing really serious (and we can coment it out in our setup if needed):
ceph-dash

**Comment by Crapworks** [comment]
Hi @richarson,

thanks for testing! I just found a typo in the pull request that I've missed before. You you check out master and try again? It should work now.

Regards,
Christian

**Comment by richarson** [comment]
Looking good now! :+1: 

ceph-dash2

**Comment by Crapworks** [comment]
Nice! Thanks for taking your time!

**Pull request merged**
